// Package costguard provides the sole LLM inference layer for Agent OS.
// All agents must call LLMClient; no agent may call an LLM provider directly.
package costguard

import (
	"context"

	"github.com/marcoantonios1/Agent-OS/internal/types"
)

// LLMClient is the interface every agent uses to request LLM inference.
// The concrete implementation routes requests through the Costguard HTTP gateway.
type LLMClient interface {
	// Complete performs a single-shot completion and returns the full response.
	Complete(ctx context.Context, req CompletionRequest) (CompletionResponse, error)
	// Stream performs a streaming completion and returns a channel of chunks.
	// The channel is closed when the stream ends or the context is cancelled.
	Stream(ctx context.Context, req CompletionRequest) (<-chan StreamChunk, error)
}

// CompletionRequest is the input to a single LLM call.
type CompletionRequest struct {
	// Model is the Costguard model identifier (e.g. "claude-sonnet-4-6").
	Model string
	// Messages is the conversation history to send as context.
	Messages []types.ConversationTurn
	// Tools are optional tool definitions the model may invoke.
	Tools []ToolDefinition
	// MaxTokens caps the response length.
	MaxTokens int
}

// CompletionResponse holds the result of a completed LLM call.
type CompletionResponse struct {
	// Content is the text generated by the model.
	Content string
	// ToolCalls contains any tool invocations the model requested.
	ToolCalls []ToolCall
	// Usage reports token consumption for cost tracking.
	Usage Usage
}

// StreamChunk is a single piece of a streaming response.
type StreamChunk struct {
	// Content is the partial text for this chunk.
	Content string
	// Done is true on the final chunk; the channel will be closed after.
	Done bool
	// Error is non-nil if the stream encountered a fatal error.
	Error error
}

// ToolDefinition describes a tool the model may call.
type ToolDefinition struct {
	// Name is the tool identifier the model uses to invoke it.
	Name string
	// Description explains what the tool does.
	Description string
	// Parameters is a JSON-schema-compatible description of the tool's inputs.
	Parameters map[string]any
}

// ToolCall represents a single tool invocation requested by the model.
type ToolCall struct {
	// ID is the opaque identifier for this call, used to correlate results.
	ID string
	// Name is the tool being invoked.
	Name string
	// Arguments is the raw JSON-encoded argument string from the model.
	Arguments string
}

// Usage reports token consumption for a single LLM call.
type Usage struct {
	PromptTokens     int
	CompletionTokens int
	TotalTokens      int
}
